name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: programs
      run: |
           cd programs
           make
           bash generaterandomdata.sh test.bin 7340032
           cp test.bin random.bin
           lizardcat-mt -z random.bin
           unlizard-mt -d random.bin.liz
           diff random.bin test.bin
           lz4-mt -z random.bin
           lz4-mt -d random.bin.lz4
           diff random.bin test.bin
           lz5-mt -z random.bin
           lz5-mt -d random.bin.lz5
           diff random.bin test.bin
           brotli-mt -z random.bin
           brotli-mt -d random.bin.brot
           diff random.bin test.bin
           zstd-mt -z random.bin
           zstd-mt -d random.bin.zst
           diff random.bin test.bin
           snappy-c-mt -z random.bin
           snappy-c-mt -d random.bin.snp
           diff random.bin test.bin
